# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-26 23:28
from __future__ import unicode_literals

import achievements.validators
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='English Title')),
                ('slug', models.SlugField(editable=False, max_length=140, null=True, unique=True)),
                ('farsiTitle', models.CharField(max_length=64, null=True, verbose_name='Farsi Title')),
                ('shortDescription', models.TextField(max_length=400, null=True, verbose_name='English Short Description')),
                ('farsiShortDescription', models.TextField(max_length=400, null=True, verbose_name='Farsi Short Description')),
                ('image', models.ImageField(upload_to='achievements/', validators=[achievements.validators.validate_file_extension_coverImage], verbose_name='عکس')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Enlgish Description')),
                ('farsiDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Farsi Descrtiption')),
            ],
            options={
                'verbose_name_plural': 'Achievements',
            },
        ),
    ]
