# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-26 23:44
from __future__ import unicode_literals

import achievements.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(upload_to='achievements/', validators=[achievements.validators.validate_file_extension_coverImage], verbose_name='Photo'),
        ),
    ]
