# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-11 22:45
from __future__ import unicode_literals

import achievements.validators
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20180427_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'دستاورد', 'verbose_name_plural': 'دستاوردها'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='farsiDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات به فارسی'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='farsiShortDescription',
            field=models.TextField(max_length=400, null=True, verbose_name='خلاصه به فارسی'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='farsiTitle',
            field=models.CharField(max_length=64, null=True, verbose_name='تیتر به فارسی'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(upload_to='achievements/', validators=[achievements.validators.validate_file_extension_coverImage], verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='shortDescription',
            field=models.TextField(max_length=400, null=True, verbose_name='خلاصه به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='تیتر به انگلیسی'),
        ),
    ]
