# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-11 22:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import landing.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='landingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vOp', models.FileField(upload_to='MPV/', validators=[landing.validators.validate_file_extension_video], verbose_name='عکس یا ویدیو')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='relatedWebsites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='نام')),
                ('link', models.CharField(max_length=256, verbose_name='تارنما')),
                ('logo', models.ImageField(upload_to='relatedWebsites/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'وبسایت مرتبط',
                'verbose_name_plural': 'وبسایت های مرتبط',
            },
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='تیتر به انگلیسی')),
                ('slug', models.SlugField(editable=False, max_length=140, null=True, unique=True)),
                ('farsi_title', models.CharField(max_length=64, verbose_name='تیتر به فارسی')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات به انگلیسی')),
                ('farsi_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیخات به فارسی')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش',
            },
        ),
    ]
