# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-12 00:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import registration.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='تیتر به انگلیسی')),
                ('farsi_title', models.CharField(max_length=64, verbose_name='تیتر به فارسی')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات به انگلیسی')),
                ('farsi_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات به فارسی')),
            ],
            options={
                'verbose_name': 'محتوی',
                'verbose_name_plural': 'محتوی',
            },
        ),
        migrations.CreateModel(
            name='registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64, verbose_name='نام')),
                ('familyName', models.CharField(max_length=64, verbose_name='نام خانوادگی')),
                ('idNumber', models.CharField(max_length=32, verbose_name='شماره کد ملی')),
                ('bsNumber', models.CharField(max_length=32, verbose_name='شماره شناسنامه')),
                ('dateOfBirth', models.CharField(max_length=16, null=True, verbose_name='تاريخ تولد')),
                ('placeofbirth', models.CharField(max_length=64, verbose_name='محل صدور شناسنامه')),
                ('bssnumber', models.CharField(max_length=64, verbose_name='شماره سريال شناسنامه')),
                ('regfor', models.CharField(max_length=16, null=True, verbose_name='داوطلب ثبت نام در')),
                ('yourreference', models.CharField(max_length=128, null=True, verbose_name='نحوه آشنايی با مدرسه')),
                ('religion', models.CharField(max_length=16, null=True, verbose_name='دين و مذهب')),
                ('personalPhoto', models.ImageField(null=True, upload_to='registered/', validators=[registration.validators.validate_file_extension_coverImage], verbose_name='عکس پرسنلی')),
                ('currentSchool', models.CharField(max_length=16, null=True, verbose_name='مدرسه فعلی')),
                ('average', models.CharField(max_length=32, null=True, verbose_name='معدل')),
                ('mathGrade', models.CharField(max_length=32, null=True, verbose_name='ریاضی')),
                ('disciplineGrade', models.CharField(max_length=32, null=True, verbose_name='انضباط')),
                ('scienceGrade', models.CharField(max_length=32, null=True, verbose_name='علوم')),
                ('specialSkillsAndTalents', models.CharField(max_length=256, null=True, verbose_name='توانایی و استعداد خاص')),
                ('fatherName', models.CharField(max_length=64, null=True, verbose_name='نام پدر')),
                ('fatherDateOfBirth', models.CharField(max_length=16, null=True, verbose_name='تاريخ تولد پدر')),
                ('fatherNationalCodeNumber', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره کد ملی پر')),
                ('fatherEdu', models.CharField(blank=True, max_length=32, verbose_name='تحصیلات پدر')),
                ('fatherprantsCouncilExp', models.CharField(max_length=32, verbose_name='سابقه عضويت در انجمن اوليا پدر')),
                ('fatherparentsCouncil', models.BooleanField(verbose_name='داوطلب عضويت در انجمن اوليا (پدر)')),
                ('fatherJob', models.CharField(max_length=512, null=True, verbose_name='شغل پدر')),
                ('fatherWorkPhone', models.CharField(max_length=32, null=True, verbose_name='تلفن محل کار پدر')),
                ('fatherPhoneNumber', models.CharField(max_length=32, null=True, verbose_name='شماره همراه پدر')),
                ('fatherEmail', models.CharField(blank=True, max_length=32, verbose_name='آدرس رايانامه پدر')),
                ('motherName', models.CharField(max_length=64, null=True, verbose_name='نام مادر')),
                ('motherDateOfBirth', models.CharField(max_length=16, null=True, verbose_name='تاريخ تولد مادر')),
                ('motherNationalCodeNumber', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره کد ملی مادر')),
                ('motherEdu', models.CharField(blank=True, max_length=32, verbose_name='تحصیلات مادر')),
                ('motherprantsCouncilExp', models.CharField(blank=True, max_length=32, verbose_name='سابقه عضويت در انجمن اوليا مادر')),
                ('motherparentsCouncil', models.BooleanField(verbose_name='داوطلب عضويت در انجمن اوليا (مادر)')),
                ('motherJob', models.CharField(max_length=512, null=True, verbose_name='شغل  مادر')),
                ('motherWorkPhone', models.CharField(max_length=32, null=True, verbose_name='تلفن محل کار مادر')),
                ('motherPhoneNumber', models.CharField(max_length=32, null=True, verbose_name='شماره همراه مادر')),
                ('motherEmail', models.CharField(blank=True, max_length=64, verbose_name='آدرس رايانامه مادر')),
                ('UM', models.CharField(blank=True, max_length=512, verbose_name='دانشگاه و رشته تحصيلی فرزند دانشگاهی')),
                ('HS', models.CharField(blank=True, max_length=32, verbose_name='وضعيت مسکن خانواده')),
                ('FS', models.CharField(blank=True, max_length=32, verbose_name='وضعيت خانواده')),
                ('WITSLW', models.CharField(max_length=128, null=True, verbose_name='دانش آموز با چه کسی زندگی ميکند؟')),
                ('houseAddress', models.CharField(max_length=256, null=True, verbose_name='آدرس منزل')),
                ('postalCode', models.CharField(max_length=32, null=True, verbose_name='کد پستی')),
                ('phoneNumber', models.CharField(max_length=16, null=True, verbose_name='شماره تلفن')),
                ('otherInfo', models.CharField(blank=True, max_length=512, verbose_name='توضيحات')),
            ],
            options={
                'verbose_name': 'درخواست ثبت نام',
                'verbose_name_plural': 'درخواست های ثبت نام',
            },
        ),
    ]
