# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-12 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import galleryApp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryName', models.CharField(max_length=64, null=True, verbose_name='نام به انگلیسی')),
                ('slug', models.SlugField(editable=False, max_length=140, null=True, unique=True)),
                ('farsiGalleryName', models.CharField(max_length=64, null=True, verbose_name='نام به فارسی')),
                ('galleryFile', models.FileField(null=True, upload_to='Galleries//', validators=[galleryApp.validators.validate_file_extension], verbose_name='آرشیو')),
                ('galleryPath', models.CharField(editable=False, max_length=256, null=True)),
                ('pictureCount', models.IntegerField(editable=False, null=True)),
                ('shortDescription', models.TextField(max_length=400, null=True, verbose_name='خلاصه به انگلیسی')),
                ('farsiShortDescription', models.TextField(max_length=400, null=True, verbose_name='خلاصه به فارسی')),
                ('coverImage', models.ImageField(null=True, upload_to='GalleryCovers/', validators=[galleryApp.validators.validate_file_extension_coverImage], verbose_name='عکس کاور')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='galleryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='نام به انگلیسی')),
                ('farsiName', models.CharField(max_length=64, null=True, verbose_name='نام به فارسی')),
                ('slug', models.SlugField(editable=False, max_length=140, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galleryApp.galleryCategory', verbose_name='Category'),
        ),
    ]
