# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-12 00:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import newsApp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='تیتر به انگلیسی')),
                ('slug', models.SlugField(editable=False, max_length=140, null=True, unique=True)),
                ('farsiTitle', models.CharField(max_length=64, null=True, verbose_name='تیتر به فارسی')),
                ('shortDescription', models.TextField(max_length=400, null=True, verbose_name='خلاصه به انگلیسی')),
                ('farsiShortDescription', models.TextField(max_length=400, null=True, verbose_name='خلاصه به فارسی')),
                ('articleImage', models.ImageField(upload_to='news/', validators=[newsApp.validators.validate_file_extension_coverImage], verbose_name='عکس کاور')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات به انگلیسی')),
                ('farsiDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات به فارسی')),
                ('date', models.CharField(max_length=64, null=True, verbose_name='تاریخ میلادی')),
                ('Farsidate', models.CharField(max_length=64, null=True, verbose_name='تاریخ شمسی')),
                ('authorName', models.CharField(max_length=64, null=True, verbose_name='نام نویسنده به انگلیسی')),
                ('farsiAuthoName', models.CharField(max_length=64, null=True, verbose_name='نام نویسنده به فارسی')),
            ],
            options={
                'verbose_name_plural': 'خبر',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farsiName', models.CharField(max_length=64, verbose_name='نام به انگلیسی')),
                ('name', models.CharField(max_length=64, verbose_name='نام به فارسی')),
                ('slug', models.SlugField(editable=False, max_length=140, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='newsApp.category', verbose_name='Categories'),
        ),
    ]
